# Generated by Django 5.0.1 on 2024-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('test_cases', models.TextField()),
                ('number_of_prompts', models.IntegerField(default=10)),
                ('use_wandb', models.BooleanField(default=False)),
            ],
        ),
    ]
